### ISSUE TITLE
Need a Code Review action for each PR

### ISSUE THREAD

**Issue by ruoyuGao** [CSCI-GA-2820-SP23-003/products#15] opened 2023-02-21 21:43 UTC
As a Developer
I need to suggest every PR should pass a code review
So that we can guaranteeing the reliability of our code
   
 ### Details and Assumptions
 - We will do code review for each PR
 - after the code has been verified, we can merge it into our master branch
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given we submit our PR
 When some one in our team approved that PR
 Then the PR could merged into master branch
```

**Comment by Hanhlin** [comment] 2023-04-03 22:13
Duplicate of #47

**Closed by Hanhlin** 2023-04-03 22:13 UTC
Labels: technical debt
